[package]
name = "tlgame-server-status-alert"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["json"] }
select = "0.6.0"
tokio = { version = "1.40.0", features = ["full"] }
serde_json = "1.0.128"
chrono = "0.4.38"
